modLoader="javafml"
loaderVersion="[43,)"
license="MIT License https://github.com/McJtyMods/FXControl/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/InControl/issues"
displayURL="http://github.com/McJtyMods/InControl/"
authors="McJty"

[[mods]]
modId="incontrol"
version="${file.jarVersion}"
displayName="InControl"
#updateJSONURL="http://myurl.me/" #optional
description='''
Be in control of spawns
'''
[[dependencies.incontrol]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.incontrol]]
    modId="lostcities"
    mandatory=false
    versionRange="[1.19-6.0.6,)"
    ordering="NONE"
    side="BOTH"
